# Generated by Django 3.2 on 2022-10-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='blood_type',
            new_name='blood_group',
        ),
    ]
