# Generated by Django 3.2 on 2022-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefined_precautions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='predefined_precautions',
            name='name',
        ),
        migrations.RemoveField(
            model_name='predefined_precautions',
            name='precaution',
        ),
        migrations.RemoveField(
            model_name='predefined_precautions',
            name='user',
        ),
        migrations.AddField(
            model_name='predefined_precautions',
            name='common_side_effects',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predefined_precautions',
            name='medicine_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predefined_precautions',
            name='medicine_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predefined_precautions',
            name='other_side_effects',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predefined_precautions',
            name='severe_side_effects',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
