# Generated by Django 3.2 on 2022-11-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_lab_report_precautions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablets_user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
